### ISSUE TITLE
Any way to retrieve submissions tags ? + cant retrieve more than the last 100 submissions

### ISSUE THREAD

**Issue by Lyfhael** [PhantomInsights/subreddit-analyzer#5]
Hey,
I was wondering if it was possible to add an option in the submission script to retrieve the posts tags ? I believe it's currently : datetime,author,title,url,domain.

Also, despite me changing those two variables : TARGET_DATE = "2019-08-31" and sys.setrecursionlimit(20000)
it always download the last 100 submissions.
Downloading: 100 submissions
No more results.

Thank you.

**Comment by Lyfhael** [comment]
@agentphantom my apology if I'm bothering you, I tag you in case you didn't get notified of my message(I'm not a regular github user so I'm not sure how it works exactly). If you didn't wish to respond then I understand, goodbye :)

**Comment by agentphantom** [comment]
Hello!

No worries, both issues can be easily resolved.

1. I think you mean post flairs, these can be obtained like this:

```
SUBMISSIONS_LIST.append(
                [iso_date, item["author"], item["title"], item["url"], domain, item["link_flair_text"])
```

2. Pushshift recently changed the maximum amount of results per query, you can only get 100 max at a time. To fix this you will only require to change both 500 to 100 (around lines 55 and 94).

**Comment by Lyfhael** [comment]
> Hello!
> 
> No worries, both issues can be easily resolved.
> 
> 1. I think you mean post flairs, these can be obtained like this:
> 
> ```
> SUBMISSIONS_LIST.append(
>                 [iso_date, item["author"], item["title"], item["url"], domain, item["link_flair_text"])
> ```
> 
> 1. Pushshift recently changed the maximum amount of results per query, you can only get 100 max at a time. To fix this you will only require to change both 500 to 100 (around lines 55 and 94).

Thank you for your reply !
Changing the 500 to 100 made it work again.
But the item["link_flair_text"] makes the script stop working.

`Traceback (most recent call last):
  File "subreddit_submissions_alt.py", line 115, in <module>
    init()
  File "subreddit_submissions_alt.py", line 40, in init
    download_submissions(subreddit=subreddit)
  File "subreddit_submissions_alt.py", line 102, in download_submissions
    [iso_date, item["author"], item["title"], item["url"], domain, item["link_flair_text"]])
KeyError: 'link_flair_text'`

So I thought : Maybe this line was the problem : 
```
        # Adding the header.
        writer.writerow(["datetime", "author", "title", "url", "domain"])
```
I changed it to
                writer.writerow(["datetime", "author", "title", "url", "domain", "link_flair_text"])

But still same error message :/

**Comment by agentphantom** [comment]
Ahh, I see.

Please try this:

```
SUBMISSIONS_LIST.append(
                [iso_date, item["author"], item["title"], item["url"], domain, item.get("link_flair_text", "")])
```

This will attempt to get the flair and if it doesn't have one it won't crash.

**Comment by Lyfhael** [comment]
> Ahh, I see.
> 
> Please try this:
> 
> ```
> SUBMISSIONS_LIST.append(
>                 [iso_date, item["author"], item["title"], item["url"], domain, item.get("link_flair_text", "")])
> ```
> 
> This will attempt to get the flair and if it doesn't have one it won't crash.

It works perfectly <3 Thank you again !
